export const TYPES = {
  RESET_STATE: "RESET_STATE",
  SET_ACTIVE_COINS_DATA: "SET_ACTIVE_COINS_DATA",
  SET_INPUT: "SET_INPUT",
  SET_OPTIONS: "SET_OPTIONS",
  SET_LOADING: "SET_LOADING",
  SET_SELECTION: "SET_SELECTION",
}
